image: golang:1.12

stages:
- test

before_script:
- mkdir -p /go/src/gitlab.bertha.cloud/partitio/Nextcloud-Partitio
- cp -r $CI_PROJECT_DIR /go/src/gitlab.bertha.cloud/partitio/Nextcloud-Partitio
- cd /go/src/gitlab.bertha.cloud/partitio/Nextcloud-Partitio/gonextcloud
- make dep

unit_tests:
  stage: test
  tags:
  - docker
  script:
  - make test

race_detector:
  stage: test
  tags:
  - docker
  script:
  - make race

code_coverage:
  stage: test
  tags:
  - docker
  script:
  - make coverage

lint_code:
  stage: test
  tags:
  - docker
  script:
  - go get -u golang.org/x/lint/golint
  - make lint
